version: '3'
services:
  stress_recognizer:
    build: ./microservices/stress_recognizer
    container_name: stress_recognizer
    restart: always
#    healthcheck:
#      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${APP_PORT}/api/v1/healthcheck/ || 1" ]
#      interval: 20s
#      timeout: 5s
#      start_period: 10s
    env_file:
      - ./microservices/stress_recognizer/.env
#    ports:
#      - '${APP_PORT}:${APP_PORT}'

  backend:
    build: ./microservices/backend
    container_name: backend
    restart: always
    #    healthcheck:
    #      test: [ "CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:${APP_PORT}/api/v1/healthcheck/ || 1" ]
    #      interval: 20s
    #      timeout: 5s
    #      start_period: 10s
    env_file:
      - ./microservices/backend/.env
#    ports:
#      - '${APP_PORT}:${APP_PORT}'
    depends_on:
      - stress_recognizer
#      stress_recognizer:
#          condition: service_healthy

