"""add table eeg

Revision ID: 271f5cde6dd4
Revises: 96ae9f73d363
Create Date: 2024-05-13 02:59:46.187626

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '271f5cde6dd4'
down_revision: Union[str, None] = '96ae9f73d363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eeg',
    sa.Column('added_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('state', sa.SmallInteger(), nullable=False),
    sa.Column('data', sa.ARRAY(sa.Double(), dimensions=2), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_app.id'], ),
    sa.PrimaryKeyConstraint('added_at', 'user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('eeg')
    # ### end Alembic commands ###
